---
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
  - name: buildpack-packager
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpack-packager.git
      branch: master
      private_key: {{buildpack-packager-private-key}}
  - name: buildpack-packager-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: buildpack-packager
      access_token: {{buildpacks-github-token}}
  - name: machete
    type: git
    source:
      uri: git@github.com:cloudfoundry/machete.git
      branch: master
      private_key: {{machete-private-key}}
  - name: machete-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: machete
      access_token: {{buildpacks-github-token}}
  - name: compile-extensions
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/compile-extensions.git
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release
  - name: nanny-time-resource
    type: time
    source:
      interval: 12h
      start: 7:00 -0400
      stop: 12:00 -0400
jobs:
  - name: buildpack-packager-specs
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack-packager
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          run:
            path: buildpacks-ci/scripts/buildpack-packager.sh
        privileged: true
  - name: machete-specs
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: machete
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: machete
          run:
            path: buildpacks-ci/scripts/machete.sh
        privileged: true
  - name: compile-extensions
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: compile-extensions
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///ruby#2.3.0
          inputs:
            - name: buildpacks-ci
            - name: compile-extensions
          run:
            path: buildpacks-ci/scripts/compile-extensions.sh
        privileged: true
